# Generated by Django 5.2.4 on 2025-07-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_create_date_alter_post_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
