# Generated by Django 5.2.4 on 2025-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_uploaded_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uploaded_File",
            field=models.FileField(blank=True, upload_to="file/"),
        ),
    ]
